FROM httpd:alpine

ADD gogrokyourself /bin/gogrokyourself

# fix linking for go binary to run in alpine
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

CMD httpd-foreground | /bin/gogrokyourself --pattern="%{COMMONAPACHELOG}"
